### ISSUE TITLE
Add typography

### ISSUE THREAD

**Issue by outofgamut** [outofgamut/HiddenWords#1]
Setup [Angular Material typography](https://material.angular.io/guide/typography) system using the Rubik + Roboto Mono pair highlighted [here](http://fonts.greatsimple.io/rubik-roboto/).

Demo the typography hierarchy anywhere you want in the home component.

**Comment by resir014** [comment]
I can take this!

**Comment by outofgamut** [comment]
great, thanks! looking over now.

**Comment by outofgamut** [comment]
resolved by #2
